using UnityEngine;

public enum ReloadType 
{
    //Magazine Weapon Type
    MAGAZINE_RELOAD,
    MAGAZINE_TACTICAL_RELOAD,
    MAGAZINE_RELOAD_SUCCESS,
    MAGAZINE_RELOAD_CANCLE,
    MAGAZINE_RELOAD_INPUTMAG,
    MAGAZINE_RELOAD_CHAMBER_READY,

    //SigleAction Weapon Type
    SINGLE_ACTION_PRELOAD,
    SINGLE_ACTION_RELOAD_INPUT,
    SINGLE_ACTION_RELOAD_CHAMBER_INPUT,
    SINGLE_ACTION_RELOAD_CHAMBER_READY,
    SINGLE_ACTION_RELOAD_CANCLE,
    SINGLE_ACTION_RELOAD_SUCCESS,
}
