//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Project/User/UserInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @UserInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @UserInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""UserInput"",
    ""maps"": [
        {
            ""name"": ""PlayerAction"",
            ""id"": ""99432a28-8198-4efc-81e2-2ef3bb2ea75b"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""bf2ef9e8-cc14-4c60-819b-925b82dc8f57"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""a8052020-804b-42f6-8dc8-50721497bbba"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""6bf75e9b-5587-4dcd-b90d-22dabf150761"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Aim"",
                    ""type"": ""Button"",
                    ""id"": ""41f5832d-9bc3-4cfc-b82b-3e84674be72b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""d2013bd1-ee9b-4a87-b228-15b98b164987"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reload"",
                    ""type"": ""Button"",
                    ""id"": ""462281fe-1585-45b8-9569-0a2dd997e2bc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwapShoulder"",
                    ""type"": ""Button"",
                    ""id"": ""8e68ab57-949c-4418-9e87-1d03575d6938"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrggerGunFuExecute"",
                    ""type"": ""Button"",
                    ""id"": ""bab15d60-90f2-4680-b0c5-32d1798bb5ee"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleChangeStance"",
                    ""type"": ""Button"",
                    ""id"": ""dcd93cd5-713d-4c60-8da6-280223c0d593"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerDodgeRoll"",
                    ""type"": ""Button"",
                    ""id"": ""fbe5934c-b573-4921-803a-60c1abd17f33"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerPickingUpWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""b6a45863-a8e4-43c5-957b-2839c283a206"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerDropWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""0ea511f6-fbca-4dd4-969f-8c454985d33e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerSwitchDrawPrimary"",
                    ""type"": ""Button"",
                    ""id"": ""0761e849-2c33-4a80-b875-e1f7c034ecfa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerSwitchDrawSecondary"",
                    ""type"": ""Button"",
                    ""id"": ""fd80c774-97ac-4411-aa68-8af1978c6660"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HolsterWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""ff9d865e-8cbd-433d-ac26-5518afd90ff8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TriggerParkour"",
                    ""type"": ""Button"",
                    ""id"": ""a48362e1-1a7f-403b-9cd8-4b78e1eb79e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""bd97236d-403e-4c41-8b95-58c4dfc9350b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ab95f5e3-1ccd-4e64-81f9-0db5c1653ebc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""55cd1dcd-4794-431e-bda9-c6aefe92f564"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""17dcdda1-5aa3-404c-9011-826554b11b3a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""dddb6801-bd57-45e7-b598-121a2f2ac16f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8398154b-ea3c-465c-9fc8-68dae45f3e72"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb308696-6813-42ef-8be3-e2f23fdb94a6"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f4e05631-0978-4601-90f2-ca08cfa7ce3b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""45664813-982a-465d-b83d-9196e2d22c4c"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a9d7f1e0-4d79-4da4-88e9-f0ecd8ef137b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""c94909da-2f19-492e-b5ba-90a91fdb3a82"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7582de8e-5933-4ae2-b5c6-87e0b09a74ba"",
                    ""path"": ""<Mouse>/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5782b070-a846-4e8d-b45b-2ff8ef491664"",
                    ""path"": ""<Mouse>/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e2c2ffa8-9f10-4a4c-8c05-8c73128cf1e8"",
                    ""path"": ""<Mouse>/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""403e9612-a873-4e24-87eb-1efa62599b4c"",
                    ""path"": ""<Mouse>/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""a78f254c-ae72-4e34-98d1-f1191151eb99"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=10,y=5)"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f9182f4c-37b0-49f3-a537-2f8dc34745a3"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""21456a32-7ceb-4c9b-b921-d7da84717f8a"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8ed7baee-45eb-480e-8ba1-d7184a4ab5ca"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""29d2afc1-407a-4d9d-8091-bb350639573e"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f14bdb77-cbcd-4450-a527-7479d4747d14"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da3fb4a9-99e6-4822-a5a0-10f8b279e01d"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1938f531-1008-45e3-a65b-40344312b48c"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28be4c52-9b08-43e5-8038-5555919ccc2c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Aim"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c6e4c7c-2b5b-4fdd-97f1-d3e1cdbe1e02"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a34f9916-9366-4580-aaf3-1fcb038d5758"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Press(pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50d0e941-c672-437a-b1b1-e53e561d679a"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""323fc9ed-c855-4d31-acfc-848c8b81d97f"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reload"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e195ec58-dc7c-4ad5-b27c-9a2d09e04c54"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef3150e3-cd68-4e3e-bdec-d82166477ab8"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwapShoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2079e9f8-8059-4712-a1e0-828e1ae6bd05"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrggerGunFuExecute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0281fe30-3535-4924-b503-78c7c4168e5f"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrggerGunFuExecute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31e08406-3802-41e0-8f89-87ef9cff83ca"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleChangeStance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ba6035-24cd-42a3-a37c-d6d4aa841b48"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleChangeStance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a396e759-2543-4ce5-a52d-c6367f45a656"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerDodgeRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60e6aa35-753a-472b-9e4c-f701577f45a9"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerDodgeRoll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41ac34d3-cff2-4c91-85d6-876d1de53a3c"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPickingUpWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""136ce3bb-c90e-435a-8fed-85d40ad10f11"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPickingUpWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c456cc0-ff16-4c9b-ae9d-9ccc100d9e40"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerDropWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba6c5146-efef-49de-9d0a-b23258572671"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerSwitchDrawPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""934a4c3c-7634-487b-8ff8-6424df3aff88"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerSwitchDrawPrimary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a6fda00-eeeb-428c-9633-fcde3206ecbe"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerSwitchDrawSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4b1f7ff-cf79-43c9-99b8-083c99f4e9ff"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerSwitchDrawSecondary"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dfa1d145-76b0-444e-b647-8358a8272c05"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HolsterWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08e1a128-aec1-4084-9ddc-d6b77c0149f3"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerParkour"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseAction"",
            ""id"": ""abee8302-3303-4230-adb2-795bc33f54be"",
            ""actions"": [
                {
                    ""name"": ""PauseTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""5124c155-39b0-4235-8a4d-95a35dfde0c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e8589ed3-dc5d-492b-8bc5-7462cb9fd242"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5f12ddc-b17b-4a2f-a761-14d50b4a2048"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerAction
        m_PlayerAction = asset.FindActionMap("PlayerAction", throwIfNotFound: true);
        m_PlayerAction_Move = m_PlayerAction.FindAction("Move", throwIfNotFound: true);
        m_PlayerAction_Look = m_PlayerAction.FindAction("Look", throwIfNotFound: true);
        m_PlayerAction_Sprint = m_PlayerAction.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerAction_Aim = m_PlayerAction.FindAction("Aim", throwIfNotFound: true);
        m_PlayerAction_Attack = m_PlayerAction.FindAction("Attack", throwIfNotFound: true);
        m_PlayerAction_Reload = m_PlayerAction.FindAction("Reload", throwIfNotFound: true);
        m_PlayerAction_SwapShoulder = m_PlayerAction.FindAction("SwapShoulder", throwIfNotFound: true);
        m_PlayerAction_TrggerGunFuExecute = m_PlayerAction.FindAction("TrggerGunFuExecute", throwIfNotFound: true);
        m_PlayerAction_ToggleChangeStance = m_PlayerAction.FindAction("ToggleChangeStance", throwIfNotFound: true);
        m_PlayerAction_TriggerDodgeRoll = m_PlayerAction.FindAction("TriggerDodgeRoll", throwIfNotFound: true);
        m_PlayerAction_TriggerPickingUpWeapon = m_PlayerAction.FindAction("TriggerPickingUpWeapon", throwIfNotFound: true);
        m_PlayerAction_TriggerDropWeapon = m_PlayerAction.FindAction("TriggerDropWeapon", throwIfNotFound: true);
        m_PlayerAction_TriggerSwitchDrawPrimary = m_PlayerAction.FindAction("TriggerSwitchDrawPrimary", throwIfNotFound: true);
        m_PlayerAction_TriggerSwitchDrawSecondary = m_PlayerAction.FindAction("TriggerSwitchDrawSecondary", throwIfNotFound: true);
        m_PlayerAction_HolsterWeapon = m_PlayerAction.FindAction("HolsterWeapon", throwIfNotFound: true);
        m_PlayerAction_TriggerParkour = m_PlayerAction.FindAction("TriggerParkour", throwIfNotFound: true);
        // PauseAction
        m_PauseAction = asset.FindActionMap("PauseAction", throwIfNotFound: true);
        m_PauseAction_PauseTrigger = m_PauseAction.FindAction("PauseTrigger", throwIfNotFound: true);
    }

    ~@UserInput()
    {
        UnityEngine.Debug.Assert(!m_PlayerAction.enabled, "This will cause a leak and performance issues, UserInput.PlayerAction.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PauseAction.enabled, "This will cause a leak and performance issues, UserInput.PauseAction.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerAction
    private readonly InputActionMap m_PlayerAction;
    private List<IPlayerActionActions> m_PlayerActionActionsCallbackInterfaces = new List<IPlayerActionActions>();
    private readonly InputAction m_PlayerAction_Move;
    private readonly InputAction m_PlayerAction_Look;
    private readonly InputAction m_PlayerAction_Sprint;
    private readonly InputAction m_PlayerAction_Aim;
    private readonly InputAction m_PlayerAction_Attack;
    private readonly InputAction m_PlayerAction_Reload;
    private readonly InputAction m_PlayerAction_SwapShoulder;
    private readonly InputAction m_PlayerAction_TrggerGunFuExecute;
    private readonly InputAction m_PlayerAction_ToggleChangeStance;
    private readonly InputAction m_PlayerAction_TriggerDodgeRoll;
    private readonly InputAction m_PlayerAction_TriggerPickingUpWeapon;
    private readonly InputAction m_PlayerAction_TriggerDropWeapon;
    private readonly InputAction m_PlayerAction_TriggerSwitchDrawPrimary;
    private readonly InputAction m_PlayerAction_TriggerSwitchDrawSecondary;
    private readonly InputAction m_PlayerAction_HolsterWeapon;
    private readonly InputAction m_PlayerAction_TriggerParkour;
    public struct PlayerActionActions
    {
        private @UserInput m_Wrapper;
        public PlayerActionActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerAction_Move;
        public InputAction @Look => m_Wrapper.m_PlayerAction_Look;
        public InputAction @Sprint => m_Wrapper.m_PlayerAction_Sprint;
        public InputAction @Aim => m_Wrapper.m_PlayerAction_Aim;
        public InputAction @Attack => m_Wrapper.m_PlayerAction_Attack;
        public InputAction @Reload => m_Wrapper.m_PlayerAction_Reload;
        public InputAction @SwapShoulder => m_Wrapper.m_PlayerAction_SwapShoulder;
        public InputAction @TrggerGunFuExecute => m_Wrapper.m_PlayerAction_TrggerGunFuExecute;
        public InputAction @ToggleChangeStance => m_Wrapper.m_PlayerAction_ToggleChangeStance;
        public InputAction @TriggerDodgeRoll => m_Wrapper.m_PlayerAction_TriggerDodgeRoll;
        public InputAction @TriggerPickingUpWeapon => m_Wrapper.m_PlayerAction_TriggerPickingUpWeapon;
        public InputAction @TriggerDropWeapon => m_Wrapper.m_PlayerAction_TriggerDropWeapon;
        public InputAction @TriggerSwitchDrawPrimary => m_Wrapper.m_PlayerAction_TriggerSwitchDrawPrimary;
        public InputAction @TriggerSwitchDrawSecondary => m_Wrapper.m_PlayerAction_TriggerSwitchDrawSecondary;
        public InputAction @HolsterWeapon => m_Wrapper.m_PlayerAction_HolsterWeapon;
        public InputAction @TriggerParkour => m_Wrapper.m_PlayerAction_TriggerParkour;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActionActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActionActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Sprint.started += instance.OnSprint;
            @Sprint.performed += instance.OnSprint;
            @Sprint.canceled += instance.OnSprint;
            @Aim.started += instance.OnAim;
            @Aim.performed += instance.OnAim;
            @Aim.canceled += instance.OnAim;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @Reload.started += instance.OnReload;
            @Reload.performed += instance.OnReload;
            @Reload.canceled += instance.OnReload;
            @SwapShoulder.started += instance.OnSwapShoulder;
            @SwapShoulder.performed += instance.OnSwapShoulder;
            @SwapShoulder.canceled += instance.OnSwapShoulder;
            @TrggerGunFuExecute.started += instance.OnTrggerGunFuExecute;
            @TrggerGunFuExecute.performed += instance.OnTrggerGunFuExecute;
            @TrggerGunFuExecute.canceled += instance.OnTrggerGunFuExecute;
            @ToggleChangeStance.started += instance.OnToggleChangeStance;
            @ToggleChangeStance.performed += instance.OnToggleChangeStance;
            @ToggleChangeStance.canceled += instance.OnToggleChangeStance;
            @TriggerDodgeRoll.started += instance.OnTriggerDodgeRoll;
            @TriggerDodgeRoll.performed += instance.OnTriggerDodgeRoll;
            @TriggerDodgeRoll.canceled += instance.OnTriggerDodgeRoll;
            @TriggerPickingUpWeapon.started += instance.OnTriggerPickingUpWeapon;
            @TriggerPickingUpWeapon.performed += instance.OnTriggerPickingUpWeapon;
            @TriggerPickingUpWeapon.canceled += instance.OnTriggerPickingUpWeapon;
            @TriggerDropWeapon.started += instance.OnTriggerDropWeapon;
            @TriggerDropWeapon.performed += instance.OnTriggerDropWeapon;
            @TriggerDropWeapon.canceled += instance.OnTriggerDropWeapon;
            @TriggerSwitchDrawPrimary.started += instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawPrimary.performed += instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawPrimary.canceled += instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawSecondary.started += instance.OnTriggerSwitchDrawSecondary;
            @TriggerSwitchDrawSecondary.performed += instance.OnTriggerSwitchDrawSecondary;
            @TriggerSwitchDrawSecondary.canceled += instance.OnTriggerSwitchDrawSecondary;
            @HolsterWeapon.started += instance.OnHolsterWeapon;
            @HolsterWeapon.performed += instance.OnHolsterWeapon;
            @HolsterWeapon.canceled += instance.OnHolsterWeapon;
            @TriggerParkour.started += instance.OnTriggerParkour;
            @TriggerParkour.performed += instance.OnTriggerParkour;
            @TriggerParkour.canceled += instance.OnTriggerParkour;
        }

        private void UnregisterCallbacks(IPlayerActionActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Sprint.started -= instance.OnSprint;
            @Sprint.performed -= instance.OnSprint;
            @Sprint.canceled -= instance.OnSprint;
            @Aim.started -= instance.OnAim;
            @Aim.performed -= instance.OnAim;
            @Aim.canceled -= instance.OnAim;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @Reload.started -= instance.OnReload;
            @Reload.performed -= instance.OnReload;
            @Reload.canceled -= instance.OnReload;
            @SwapShoulder.started -= instance.OnSwapShoulder;
            @SwapShoulder.performed -= instance.OnSwapShoulder;
            @SwapShoulder.canceled -= instance.OnSwapShoulder;
            @TrggerGunFuExecute.started -= instance.OnTrggerGunFuExecute;
            @TrggerGunFuExecute.performed -= instance.OnTrggerGunFuExecute;
            @TrggerGunFuExecute.canceled -= instance.OnTrggerGunFuExecute;
            @ToggleChangeStance.started -= instance.OnToggleChangeStance;
            @ToggleChangeStance.performed -= instance.OnToggleChangeStance;
            @ToggleChangeStance.canceled -= instance.OnToggleChangeStance;
            @TriggerDodgeRoll.started -= instance.OnTriggerDodgeRoll;
            @TriggerDodgeRoll.performed -= instance.OnTriggerDodgeRoll;
            @TriggerDodgeRoll.canceled -= instance.OnTriggerDodgeRoll;
            @TriggerPickingUpWeapon.started -= instance.OnTriggerPickingUpWeapon;
            @TriggerPickingUpWeapon.performed -= instance.OnTriggerPickingUpWeapon;
            @TriggerPickingUpWeapon.canceled -= instance.OnTriggerPickingUpWeapon;
            @TriggerDropWeapon.started -= instance.OnTriggerDropWeapon;
            @TriggerDropWeapon.performed -= instance.OnTriggerDropWeapon;
            @TriggerDropWeapon.canceled -= instance.OnTriggerDropWeapon;
            @TriggerSwitchDrawPrimary.started -= instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawPrimary.performed -= instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawPrimary.canceled -= instance.OnTriggerSwitchDrawPrimary;
            @TriggerSwitchDrawSecondary.started -= instance.OnTriggerSwitchDrawSecondary;
            @TriggerSwitchDrawSecondary.performed -= instance.OnTriggerSwitchDrawSecondary;
            @TriggerSwitchDrawSecondary.canceled -= instance.OnTriggerSwitchDrawSecondary;
            @HolsterWeapon.started -= instance.OnHolsterWeapon;
            @HolsterWeapon.performed -= instance.OnHolsterWeapon;
            @HolsterWeapon.canceled -= instance.OnHolsterWeapon;
            @TriggerParkour.started -= instance.OnTriggerParkour;
            @TriggerParkour.performed -= instance.OnTriggerParkour;
            @TriggerParkour.canceled -= instance.OnTriggerParkour;
        }

        public void RemoveCallbacks(IPlayerActionActions instance)
        {
            if (m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActionActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActionActions @PlayerAction => new PlayerActionActions(this);

    // PauseAction
    private readonly InputActionMap m_PauseAction;
    private List<IPauseActionActions> m_PauseActionActionsCallbackInterfaces = new List<IPauseActionActions>();
    private readonly InputAction m_PauseAction_PauseTrigger;
    public struct PauseActionActions
    {
        private @UserInput m_Wrapper;
        public PauseActionActions(@UserInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseTrigger => m_Wrapper.m_PauseAction_PauseTrigger;
        public InputActionMap Get() { return m_Wrapper.m_PauseAction; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseActionActions set) { return set.Get(); }
        public void AddCallbacks(IPauseActionActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseActionActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseActionActionsCallbackInterfaces.Add(instance);
            @PauseTrigger.started += instance.OnPauseTrigger;
            @PauseTrigger.performed += instance.OnPauseTrigger;
            @PauseTrigger.canceled += instance.OnPauseTrigger;
        }

        private void UnregisterCallbacks(IPauseActionActions instance)
        {
            @PauseTrigger.started -= instance.OnPauseTrigger;
            @PauseTrigger.performed -= instance.OnPauseTrigger;
            @PauseTrigger.canceled -= instance.OnPauseTrigger;
        }

        public void RemoveCallbacks(IPauseActionActions instance)
        {
            if (m_Wrapper.m_PauseActionActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseActionActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseActionActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseActionActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseActionActions @PauseAction => new PauseActionActions(this);
    public interface IPlayerActionActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnAim(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnReload(InputAction.CallbackContext context);
        void OnSwapShoulder(InputAction.CallbackContext context);
        void OnTrggerGunFuExecute(InputAction.CallbackContext context);
        void OnToggleChangeStance(InputAction.CallbackContext context);
        void OnTriggerDodgeRoll(InputAction.CallbackContext context);
        void OnTriggerPickingUpWeapon(InputAction.CallbackContext context);
        void OnTriggerDropWeapon(InputAction.CallbackContext context);
        void OnTriggerSwitchDrawPrimary(InputAction.CallbackContext context);
        void OnTriggerSwitchDrawSecondary(InputAction.CallbackContext context);
        void OnHolsterWeapon(InputAction.CallbackContext context);
        void OnTriggerParkour(InputAction.CallbackContext context);
    }
    public interface IPauseActionActions
    {
        void OnPauseTrigger(InputAction.CallbackContext context);
    }
}
